# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('N', 'Newsletter message'), ('O', 'Opt-in confirmation')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletters.Edition'),
        ),
    ]
