# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20160627_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 27, 20, 57, 52, 707209, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edition',
            name='display_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 6, 27, 20, 57, 57, 77163, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plaintextdraft',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 27, 20, 58, 1, 435183, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortlink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 27, 20, 58, 5, 651151, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
