# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_auto_20160627_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='list_info_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='list_info_header',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
