# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0005_auto_20160627_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='reply_to_email_address',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
